// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Server from "react-dom/server";

function f(x) {
  if (x === null) {
    return ;
  } else {
    return Caml_option.some(x);
  }
}

console.log("foo");

console.log(Server.renderToStaticMarkup(React.createElement("div", undefined, "Hello world")));

export {
  f ,
  
}
/*  Not a pure module */
