// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function f(x) {
  if (x === null) {
    return ;
  } else {
    return Caml_option.some(x);
  }
}

export {
  f ,
  
}
/* No side effect */
